package midterm2Review;

import java.io.IOException;
import java.util.Random;

//https://rollbar.com/wp-content/uploads/2021/07/java-exceptions-hierarchy-example.png
public class ExceptionsRe {
	public static void main(String[] args) throws IOException, ZeroGenerated{
		Random r = new Random();
		int i = r.nextInt(2);
		try {
			if(i==0) {
	//			throw a custom exception
				throw new ZeroGenerated("0 generated by random");
			}
		} catch (ZeroGenerated e) {
			System.out.println(e.getMessage());
		} finally {
			System.out.println("Try catch finished executing");
		}
		
		
		
		
		// block of code for file writing
	}
}

class ZeroGenerated extends Exception{
	public ZeroGenerated(String message) {
		super(message);
	}
}


/*try {
	// the code you are trying to execute
}

catch (<Specific_Exception> e) {
	//handle that exception
}
catch (<Specific_Exception> e) {
	//handle that exception
}
catch (<Specific_Exception> e) {
	//handle that exception
}
catch (Exception e) {
	// the code that will execute if there is an exception in 
	// the try block.
	// stacktrace: how the exception occured 
	
	// with try, you need atleast 1 catch block
	
	// serves as catch all block
}
finally {
	// is always executed
}
*/