package midterm2Review;

import java.io.IOException;
import java.util.Random;
//https://rollbar.com/wp-content/uploads/2021/07/java-exceptions-hierarchy-example.png
public class ExceptionsReview {
	public static void main(String[] args) throws IOException,ZeroGenerated {
		Random r = new Random();
		int i = r.nextInt(2);
		try {
			if(i==0) {
				throw new ZeroGenerated("0 generated by random");
			}
		} catch (ZeroGenerated e) {
			System.out.println(e.getMessage());
		} finally {
			System.out.println("Finished random");
		}
		
		// if any code that can throw IOException
	}
}

class ZeroGenerated extends Exception{
	public ZeroGenerated(String message) {
		super(message);
	}
}


/*
try {
	// code that you are trying to execute
}
catch (<Specific_Exception eg ArithmeticException> e) {
	//handle Specific_Exception
}
catch (<Exception> e) {
	// exception handling part
	// 1 or more than 1 catch block
	// Exception catches all exception --- catch all block
	// catch all should be the catch block
}
finally {
	// code that will be executed regardless of the try/catch result
}

*/
